force-app/main/default/objects/FD_Details__c/FD_Details__c.object-meta.xml
<CustomObject>
    <label>FD Details</label>
    <nameField>
        <displayFormat>FD-{00000}</displayFormat>
        <label>FD Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FD Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FD_Details__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Senior_Citizen</fullName>
                <label>Senior Citizen</label>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FD_Details__c/fields/Deposit_Type__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Type__c</fullName>
    <label>Deposit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cumulative</fullName>
            </value>
            <value>
                <fullName>Non-Cumulative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FD_Details__c/fields/FD_Amount__c.field-meta.xml
<CustomField>
    <fullName>FD_Amount__c</fullName>
    <label>FD Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/FD_Details__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Interest Rate</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/FD_Details__c/fields/Interest_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Interest_Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interest Scheme</label>
    <referenceTo>Interest_Scheme__c</referenceTo>
    <relationshipLabel>FD Details</relationshipLabel>
    <relationshipName>FD_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FD_Details__c/fields/Payout_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payout_Frequency__c</fullName>
    <label>Payout Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Deposit_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half Yearly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FD_Details__c/fields/Tenor_in_Days__c.field-meta.xml
<CustomField>
    <fullName>Tenor_in_Days__c</fullName>
    <label>Tenor in Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FD_Details__c/fields/Tenor_in_Months__c.field-meta.xml
<CustomField>
    <fullName>Tenor_in_Months__c</fullName>
    <label>Tenor in Months</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/fetchScheme.cls
public with sharing class fetchScheme {

  @AuraEnabled(cacheable=true)
  public static FD_Details__c fetchCustomerType(string fdId){
      return [SELECT Customer_Type__c, Id 
      FROM FD_Details__c 
      WHERE Id=:fdId
      WITH SECURITY_ENFORCED];
  }


  @AuraEnabled 
  public static list<Interest_Scheme__c> fetchInterestScheme(string custType, string depType, integer tenMonths, integer tenorDays, integer fdAmount, string fdId){

      return [SELECT Id, Name, Tenor_From_Days__c, Tenor_To_Days__c, Tenor_From_Months__c, Tenor_To_Months__c, Customer_Type__c, Interest_Rate__c, Deposit_Type__c, From_Amount__c, To_Amount__c 
      FROM Interest_Scheme__c
      WHERE Customer_Type__c=:custType 
      AND Deposit_Type__c=:depType
      AND Tenor_From_Days__c<=:tenorDays
      AND Tenor_To_Days__c>=:tenorDays
      AND Tenor_From_Months__c<=:tenMonths
      AND Tenor_To_Months__c>=:tenMonths
      AND From_Amount__c<=:fdAmount
      AND To_Amount__c>=:fdAmount 
      WITH SECURITY_ENFORCED];
      

      
  }

  // dml -> update -> cause we are updating an existing record values with the ones user entered
  @AuraEnabled
  public static void updateFD(string depType,string payFreq, integer tenMonths,integer tenDays, decimal fdAmount, string inScheme, string fdId, decimal inRate ){

      FD_Details__c fd=new FD_Details__c();//object - instance
      fd.Id=fdId;
      fd.Deposit_Type__c=depType;
      fd.Payout_Frequency__c=payFreq;
      fd.Tenor_in_Months__c=tenMonths;
      fd.Tenor_in_Days__c=tenDays;
      fd.FD_Amount__c=fdAmount;
      fd.Interest_Scheme__c=inScheme;
      fd.Interest_Rate__c=inRate;
      update fd;



      
      
  }





}